### PR TITLE
Make use of caching system in base adapter

### LINKED ISSUE #417: Make use of Caching system
#### Description:

Tweak all read methods in Etabs to make use of the caching system added in https://github.com/BHoM/BHoM_Adapter/pull/337

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/337
intentionally using different branch names to let the Adapter PR be merged separately.

 ### Issues addressed by this PR

 Closes #417 

 

Make use of the Caching system added to the Base adapter. Aim for this to speed up the push process, especially for higher level objects.

 ### Test files

Usual test file for Push/Pull:
- https://burohappold.sharepoint.com/:f:/s/BHoM/EgweOoPLfH1Jp4af3nYl9zwBN-fusTnBgRggWimsp2knVA?e=u3D3RD
- https://burohappold.sharepoint.com/:f:/s/BHoM/EqPyIzrdkF9CvI0_e85Bo-sBrlNc1B1Z6u8lyrDBUKL-iw?e=udkEMR

The testing should simply verify that things work as good as usual.
This PR only makes backend improvements to the Adapter and should not affect existing workflows.

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by hmoubarak — APPROVED** [review]
I built the branch and tested the functionality with the test files. All seems ok. Code not reviewed.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Review by alelom — APPROVED** [review]
Approving on the basis of code changes only.

**Pull request merged**
