### PR TITLE
Fix the dispatching done by the Update method

### LINKED ISSUE #325: ETABS_Toolkit: Update is not dispatching properly for some types
#### Description:

Update of sections and material is not working properly. Update dispatcher does not find the correct method.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EqKCe0ee8wROoq24ANb0-r0BTUvkH_h4vJ8kHiyFesXtKw?e=uAYGlv

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #325 

 

Fix the dispatching done by the Update method

 ### Test files

 ### Changelog

https://burohappold.sharepoint.com/:f:/s/BHoM/EqKCe0ee8wROoq24ANb0-r0BTUvkH_h4vJ8kHiyFesXtKw?e=tp6GTX

https://burohappold.sharepoint.com/:f:/s/BHoM/EgLyzStwfWpGi7sSnAxSKNYBIyRhMp90JNyRQ_ozaUD-9g?e=ggV4Jt

 ### Additional comments

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@IsakNaslundBh There's an issue with this, I wanted to be sure you know before merging, but also wanted to be sure you can merge before I wake up if it's OK

**Comment by IsakNaslundBh** [comment]
Hmm, all working fine for me. Unless something else urgent needs fixing on ETABS, I will leave this open until you come online, and we can check together.

**Comment by JosefTaylor** [comment]
Issue resolved, was my fault!

**Pull request merged**
