### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Update Assembly Version to 5.0.0.0
Update Assembly File Version to 5.0.0.0

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from DevOps, will leave merge to toolkit lead or will merge automatically on 29th September 2021.

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning
@BHoMBot check serialisation
@BHoMBot check project-compliance
@BHoMBot check null-handling
@BHoMBot check document-compliance
@BHoMBot check copyright-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check documentation-compliance
@BHoMBot check code-compliance

**Pull request merged**
