### PR TITLE
Etabs toolkit issue111 do not ignore ids and cases for bar force

### LINKED ISSUE #111: ETABS_Toolkit: BarForce ignores cases and ids from query
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #111  
There's some funny commit history that I hope will dissapear in the merge, because I accidentally committed into a local copy of the last branch which had just been merged, then merged into the new branch to fix it. If you'd rather I started fresh, let me know.

**PREVIOUSLY PR'ED HERE:**
https://github.com/BHoM/ETABS_Toolkit/pull/112

Re PR'ed here to solve the rebase/merge issue for @IsakNaslundBh

### CODE REVIEW

**Comment by JosefTaylor** [comment]
Thanks for rePRing. I'm having trouble synching the new branch (my GitHub client thinks I have some commits) so hopefully someone else can compile, test, and merge and I'll just catch up with myself then.

**Comment by FraserGreenroyd** [comment]
@JosefTaylor are you using GitHub Desktop or Git Bash?

Feel free to give me a shout on Skype, I can walk you through sorting out your local branch issue - but the essentials are just to delete the local branch and refetch from the remote here :smile:

**Comment by JosefTaylor** [comment]
> Feel free to give me a shout on Skype, I can walk you through sorting out your local branch issue - but the essentials are just to delete the local branch and refetch from the remote here smile

Ding ding! that sussed it. I'll compile and test.

**Comment by al-fisher** [comment]
Thanks @FraserGreenroyd and @JosefTaylor 
@enarhi or @IsakNaslundBh - can either of you two please Test and hopefully confirm success with an Approval. Following this we can the merge. Cheers

**Comment by IsakNaslundBh** [comment]
Some problem pulling results when providing no loadcases, and if there where no loadcombinations in the model. might have been a problem before, but needed fixing. Fix for it Pushed.

Also, moved the case check to a separate method, as same for all the current result.

Test file here:

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/ETABS_Toolkit_Issue111_LoadExtraction?csf=1&e=HbD2GF

**Pull request merged**
