### PR TITLE
Add implementation of Exit command

### LINKED ISSUE #387: Add support for Exit command
#### Description:

Add implementation of Exit command added in https://github.com/BHoM/BHoM_Adapter/issues/302

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/303

 ### Issues addressed by this PR

 Closes #387

 

Adding support for the Exit command

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EjpTgU6jo_tJr30rbJs0a_gBnZnhI1rYcv3aQ-Yc3A6E2g?e=fenJ0J

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by JosefTaylor — DISMISSED** [review]
Perfect!

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
After discussions in https://github.com/BHoM/Robot_Toolkit/pull/466#issuecomment-904922155 Added check for if file path existed before trying to exit if the `SaveBeforeClose` option is true

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by alelom — APPROVED** [review]
LGTM. Tested with ETABS, works as expected.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Pull request merged**
