### PR TITLE
Fixes the issue of failing to launch ETABS application when the ETABS adapter is toggled on

### LINKED ISSUE #420: Etabs Adapter is not able to launch Etabs
#### Description:
When using the Etabs adapter and toggling it to active, it doesn't seem to be able to launch Etabs. It does start doing it, showing the etabs start-up frame on my screen. But then it closes off and gives this error:

_1. This component failed to run properly.
- Error: Failed to read from an IPC Port: The pipe has been ended. - Occured in  BH.Adapter.ETABS.ETABSAdapter..ctor(String filePath, EtabsSettings etabsSetting, Boolean active)
     called from BH.UI.Base.Caller.Run(List`1 inputs)
- Are you sure you have the correct type of inputs? Check their description for more details._

When I already have etabs open, it does work. So the problem is in the launching. I have Etabs 19 installed.

#### Steps to reproduce:
Just use the etabs adapter and set it to active.

#### Expected behaviour:
That it can launch etabs.

#### Test file(s):
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/Issue%20Etabs%20Adapter%20is%20not%20able%20to%20launch%20Etabs/[Etabs_fail.gh](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/Issue%20Etabs%20Adapter%20is%20not%20able%20to%20launch%20Etabs/Etabs_fail.gh?csf=1&web=1&e=vJihll)?csf=1&web=1&e=vJihll

### PR DESCRIPTION
**Pull request by samuelbasimalla**
### Issues addressed by this PR

 Closes #420 

 

 ### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/ETABS_Toolkit/%23420%20Issue%20Etabs%20Adapter%20is%20not%20able%20to%20launch%20Etabs/240205%20Etabs_Launch%20fail_Resolved.gh?csf=1&web=1&e=IGX2gI

 ### Changelog

Replaced ETABSv1 with CSiAPIv1 NuGet package. This causes the ETABS Application to be launched when the adapter component is toggled on.

 ### Additional comments

ETABS adapter would fail to launch ETABS (Version 19) as reported by the user. The push/pull would only work when the ETABS application is already opened by the user manually. The reported behavior is also observed in ETABS (Version 20) which is the version installed in my machine. Replacing of NuGet Package with more updated version (which references CSI ETABS API) fixed this issue.

### CODE REVIEW

**Review by sonyaqaderi — DISMISSED** [review]
Tested using the 240214 alpha version. The code works and open ETABS 20 when the adaptor is toggled on in Grasshopper.

**Comment by adityaramboll** [comment]
@sonyaqaderi  What Version of ETABS were you testing it with ?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 21586002084

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Approving in line with [this review](https://github.com/BHoM/ETABS_Toolkit/pull/444#pullrequestreview-1880064443) as only commit since that review has been the bot for project compliance.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
