### PR TITLE
Different .dll names per Build Configuration

### LINKED ISSUE #189: Etabs_Toolkit: Build different dlls for different versions of Etabs
#### Description:

The returning dlls of the adapter for etabs need to have different names depending on version of Etabs.

Example:

`Etabs2016_Adapter`
`Etabs2016_Engine`

Also need to investigate if the class name need to be changed as well.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

 Closes #189 
Please read the comment below for the question.

Also sets `CopyLocal` to `false` for all refs except ETABS's (https://github.com/BuroHappoldEngineering/Operations_Toolkit/issues/92)

Also sets AssemblyFileVersion to `2.4.0.0` (https://github.com/BuroHappoldEngineering/Operations_Toolkit/issues/77)
 

 ### Changelog

* Added workaround to reference two different ETABS .dlls: 2016 and 2017
  * Removed dependencies to ETABS dlls from the ETABS_Engine. Moved all methods that needed those refs from Engine to Adapter.
  * We therefore produce a different ETABS Adapter (`ETABS2016Adapter` or `ETABS2017Adapter`) depending on the build configuration, but only one ETABS_oM and ETABS_Engine.
  * This means that any difference in CSI's ETABS dlls versions will have to be tackled inside the Adapter and not in the Engine.
* `CopyLocal` set to `false` for all refs except ETABS's.
* `AssemblyFileVersion` set to `2.4.0.0`

### CODE REVIEW

**Comment by alelom** [comment]
Realised there is a "multiplication" problem if both version are compiled/installed.

   Adapter 
   image

   any method
   image

raising discussion @IsakNaslundBh @epignatelli @adecler @epignatelli @al-fisher @rwemay 

Potential workarounds:
1. Keep the multiplied methods, but work on the BH.Engine.Reflection.ToText() method to expose a suffix "_2016", "_2017", etc. to the methods
2. Officially support only one version at a time, leaving the option of which one be available at install time
3. any other idea/thought?

**Comment by IsakNaslundBh** [comment]
could also solve this with precompiler directives I guess. They would need to end up in quite a few places though, basically every file in the adapter project, but probably the only real solution I can think of. would mean something like this:

```
namespace BH.Adapter.ETABS
{
#if Debug2017
    public partial class ETABS2017Adapter : BHoMAdapter
#else
    public partial class ETABS2016Adapter : BHoMAdapter
#endif
    {

```

at for each declaration. Not liking this to much, but might solve the problem.

Could then also try to get rid of any etabs dependency in the engine and move the support methods over to the adapter so we can get away with only one etabs_Engine.

**Comment by alelom** [comment]
Hey @IsakNaslundBh thanks for your input!
I can't see how that approach would solve the fundamental problem of having two "duplicate" methods (one per .dll): you'd still have to choose which version to install. I guess what you're really saying is that you'd go for option 2 above?
As you say, the problem with option 2 is that every time you have a call to an ETABS method you should have a preprocessor directive.

**Comment by IsakNaslundBh** [comment]
What I am saying is kind of two fold.

1. Using pre-processor directives on the Etabs_Adapter project
2. Get rid of any dependency on the Etabs dlls in the Etabs_Engine and move those methods over to the adapter -> no need to make two separate builds -> problem with duplicate method calls is gone.

**Comment by adecler** [comment]
I guess the main question for me is why do we need different names for the Etabs dlls in the first place ? 

Revit is usually the biggest offender and even it doesn't require differentiating names for the engine and the adapter.

**Comment by IsakNaslundBh** [comment]
@adecler the difference is that Revit has a separation between the COM-side of the adapter and the UI-side of the adapter.

For Revit we have a small class called RevitAdapter, which is only a simple Socket dispatcher that sends data to the process on the Revit side where all the interop calls are made. On the revit side we _do_ have different dlls, one for 2018 and one for 2019, it is just that they do not show up in the UI.
This is all really just a sort of positive side effect coming from how we had to deal with communicating with revit.

Etabs does not have any of this wrapper stuff, but instead only has one adapter project, nothing more. Same as Revit it does rely on separate dlls between versions, were some calls are needed to be made in a slightly different way, hence the need for different builds.

I do think we should try to get away with only one engine, but don't think we can get around the need for two adapters. One alternative would be to do the same as for Revit, to build a small wrapper UI-side project, but not to fond of that idea tbh. Then would prefer to have a `Etabs2016Adapter` and a `Etabs2017Adapter`.

Does this make sense? Or if you have a better way to solve this it would ofc be more than appreciated, just have not thought of any myself so far.

**Comment by adecler** [comment]
Summary of chat with @IsakNaslundBh :
- The solution provided above is fine for this sprint but we should avoid peppering preprocessor directives all around the code. This PR should be merged with the condition that an issue was raised to fix that.
- In term of class names and `using` directives, we can use the pre-build process to replace the values appropriately. This is more a C feature and is not directly supported in C# but we can use VS to our advantage (as long as it still play nicely with our CI tools). Worst case scenario, we have to make a temporary copy of the cs files so we can modify them before compiling.
- In term of the parts of the code that are different for each version, I think we should isolate that to a Initialisation method called by the constructor (or statically). In the example of ETABS, we just need to initialise a string (for the target path) and a helper based on the version. Everything else in the code will just reference them without having to worry about the version.

**Comment by alelom** [comment]
Probably the worst fix/workaround I have ever had to do 😿

**Comment by epignatelli** [comment]
Sorry - late to the party.

Have you also considered using aliases?
Something like:

AdapterVersions.cs
```c#
public static partial class ETABS2017Adapter : BHoMAdapter { }

public static partial class ETABS2016Adapter : BHoMAdapter { }

public static partial class ETABSAdapter : BHoMAdapter()
```

```c#
#if Debug17
using ETABSAdapter = ETABS2017Adapter;
#else
using ETABSAdapter = ETABS2016Adapter;
#endif
```

Not sure if that could work though. The principle is that you use `partial class`es and fill just the one you need.

**Comment by JosefTaylor** [comment]
> Have you also considered using aliases?

I would love this if it allows us to get the engine methods back to the engine- that's super weird.

(though having a convert namespace in the adapter, and getting rid of the engine would also be fine)

**Comment by alelom** [comment]
@IsakNaslundBh, @JosefTaylor, I've done a bit of cleanup to make this more acceptable:
- The _Engine methods are reduced to the essential: only those that are using classes from the API
- Some Engine methods that were used only as support methods for the core Adapter methods are moved there (some of them were not respecting the Engine compliance)

I did consider using the Aliases as @epignatelli suggested -- thank you btw! -- however I can't see how they can be of help. We do need to have two different Adapter classes (with 2 different names) in order for them to be recognisable in the menu.

**Comment by IsakNaslundBh** [comment]
Works fine for me now!

**Pull request merged**
