### PR TITLE
Fix Etabs unlock/delete results function

### LINKED ISSUE #350: Command "ClearResults" does not unlock model
#### Description:

Currently the command `ClearResults` deletes the results successfully, but the model remains locked. This is a condition which generally never occurs in normal use, so would be confusing to the user. Automated workflows would also fail to make changes, unless another command unlocks the model.

#### Expected behaviour:

When `ClearResults` is executed, it should also unlock the model.

### PR DESCRIPTION
**Pull request by junjieim**
### Issues addressed by this PR

Resolves #350

 ### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/Burohappold_BHoM_v6.3/Structures%20-%20Execute%20commands/BuroHappold_BHoM_v6.3.beta_ExecuteCommands.gh?csf=1&web=1&e=0fKUaa

 ### Changelog

- Fixed Etabs `ClearResults` function so the model becomes unlocked.

 ### Additional comments

Previous `ClearResults` command does not work but still return `true`.
Fix this bug by referring to the code of sap2000 toolkit.

### CODE REVIEW

**Review by peterjamesnugent — APPROVED** [review]
Good first PR @junjieim - I have reviewed using the test script (on @sonyaqaderi's machine) and it works as intended.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge

**Comment by FraserGreenroyd** [comment]
@junjieim thanks for the contribution! 😄 I just wanted to let you know that this has made it into the 6.3 beta which will be produced tomorrow and be available on the BHoM.xyz website early next week 😄

**Pull request merged**
