### PR TITLE
Pulling Grids Enabled

### LINKED ISSUE #167: ETABS_Toolkit : Pull Grids
With reference to issue: https://github.com/BHoM/ETABS_Toolkit/issues/69
Feature also required to query Levels/Storeys and Grids.

### PR DESCRIPTION
**Pull request by kThorsager**
### Issues addressed by this PR
 Closes #167 
Allows one to pull Grids.

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/ErtGvZWnFulIt40Isz-1pNkB46Y_w0eQBAKLSOnfpAdt8Q?e=X0Oh4P

### CODE REVIEW

**Comment by kThorsager** [comment]
Ok, I'll give it a go,
And to make clear, the free-form grids you mention are the general grids which are lines?

**Comment by IsakNaslundBh** [comment]
> Ok, I'll give it a go,
> And to make clear, the free-form grids you mention are the general grids which are lines?

Yes, exactly.  It is the ones you can add by "Draw Grid":

image

**Comment by kThorsager** [comment]
Your suspicions were well founded @IsakNaslundBh and the unit conversion seems to happen at a method level and is bypassed by using the explicit angular method (GetCylindricalGrids)

Think I tested and it worked for different unit setting for ETABS

**Comment by IsakNaslundBh** [comment]
@nirbhay93 FYI. Pulling of Grid is now added and should be available in tomorrows alpha.

**Pull request merged**
