### PR TITLE
Align with rename StartNode/EndNode to Start/End

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1579

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by Tom-Kingstone — APPROVED** [review]
Approved, see message in linked PR.

**Pull request merged**
