### PR TITLE
Update Read.cs

### LINKED ISSUE #162: Etabs_Toolkit: Failing to pull bar with explicit offset

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #162 

 

adding missed instantiation of offset class before trying to modify it

### CODE REVIEW

**Comment by JosefTaylor** [comment]
mass of bar according to BHoM Engine does not reflect end length offset, other than that it all works!

**Comment by IsakNaslundBh** [comment]
Good point Josef, but as you know and state, that is something we need to tweak in the mass method in the BHoM_Engine and not here. Maybe add some options in there for inclusion of offsets or not in the mass calc! Would you mind raising an issue for it?

**Comment by JosefTaylor** [comment]
Agreed, though there's also the issue of two options for self mass in ETABS: weight from full length or weight from clear length. So maybe we also need a boolean in the offset object which tells us whether to count the mass/weight of the object within the offset region.

**Comment by IsakNaslundBh** [comment]
true. That would be another way to solve it. Or maybe a combination of both. Anyhow, will merge this in now:)

**Pull request merged**
