### PR TITLE
ETABS_Engine: Capitalise ETABS_Engine assembly name

### LINKED ISSUE #367: ETABS_Engine.dll is not capitalised in the same way as other ETABS DLLs
image

ETABS_oM and ETABS_Engine DLLs are not capitalised the same way. It appears that the full capitalisation is correct based on the adapters and the repo name, so probably best to change Etabs_Engine to ETABS_Engine - but if that is not correct then please fix the others instead 😄

### PR DESCRIPTION
**Pull request by IsakLarbornBH**
### Issues addressed by this PR

 Closes #367

 
Changes assembly name from Etabs_Engine to ETABS_Engine to match the capitalisation used throughout the toolkit. This means that Etabs_Engine.dll will now be called ETABS_Engine.dll. Note that files in Windows are not case sensitive, so if Etabs_Engine.dll already exists when building, this name will be kept - but this should also mean that this change shouldn't cause any File Not Found errors or similar.

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
I'm happy from a CI perspective only, will leave @IsakNaslundBh to approve from functionality and discipline.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by IsakNaslundBh** [comment]
I am having some quite strange build issues on my machine:

image

Can not see how the change made in the PR would affect this, and have never experienced it before, so not really sure what is going on here, but need to investigate before approving.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
Reason I have not experienced the build issue before probably links back to https://github.com/BHoM/BHoM_Engine/pull/2251

Still find it strange that both Diffing_Engine and Structure_Engine builds fine to 4.5.2 when the ETABS_Engine does not...

**Comment by IsakLarbornBH** [comment]
That is pretty odd. It builds just fine on my end, on top of the latest installer.

**Comment by IsakNaslundBh** [comment]
> That is pretty odd. It builds just fine on my end, on top of the latest installer.

Had some other people test building as well, namely @alelom and @adecler and neither of them had any issues building. Might be my machine just behaving weirdly. Will restart it later today and check again, which hopefully resolves it. No need for you to look any closer on this until I have done that @IsakLarbornBH !

**Review by JosefTaylor — APPROVED** [review]
This ran just fine for me

**Pull request merged**
