### PR TITLE
Change inheritance for PierForce

### LINKED ISSUE #447: Change inheritance for PierForce class
#### Broken rules:

`PierForce` should be a seperate BarResult, rather than inherit `BarForce`.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

 Closes #447 

 

 ### Test files

https://burohappold.sharepoint.com/:u:/s/BHoM/EWEdqsW6RwlKipogK2deoTIBaMctYiF38inJzHUCDtG19g?e=opbGFs

 ### Changelog

- Updated inheritance for `PierForce` and removed inheritance of `BarForce`;

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by GCRA101 — APPROVED** [review]
I've tested the code using the latest Alpha of the BHoM on the date 06/08/2024.
I've used the grasshopper script #445-ChangeInheritancePierForce.gh for the test and the parameters of the PierForce objects are extracted as expected.
See screenshots attached for evidence.
GHScriptWithOutputs


@peterjamesnugent 

Changes approved.

**Review by GCRA101 — APPROVED** [review]
Tested the code directly exporting the pier forces from a sample etabs model.
All working fine and as expected.

Changes approved.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by GCRA101** [comment]
@IsakNaslundBh , @Chrisshort92 ,
thank you for reviewing and for your comments.
I've updated the inheritance of the SpandrelForce Class to be from BarResult rather than from BarForce.

Updated code pushed to origin for your final check.

SpandrelForceClassInheritance

**Pull request merged**
