### PR TITLE
Fix boolean check on Bar update

### LINKED ISSUE #424: Bar update is not working
#### Description:

Due to a flipped check here:
https://github.com/BHoM/ETABS_Toolkit/blob/b86525f1fef92cef300064cb1614e32c623959d1/Etabs_Adapter/CRUD/Update/Bar.cs#L54-L58

Bars can simply not be updated.

Check needs to be reversed.

#### Steps to reproduce:

Try to update a bar

#### Expected behaviour:

For bars with set IDs to be able to be updated

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #424

 

Correct check for adapter id for Bar update

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by Chrisshort92** [comment]
Push Error Message "1. The BHoM does not currently explicitly support sections of material type Undefined. A generic section has been created with the material applied to it". The material does push correctly to the correct sections as seen in the image.

image

Pushing Bars & Updating bars take place correctly with materials and section sizes updating.

Functionality passes.

**Review by Chrisshort92 — APPROVED** [review]

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
See [this review](https://github.com/BHoM/ETABS_Toolkit/pull/425#issuecomment-1473747981) from @Chrisshort92 which states functionality is passing, but just isn't contained in an approving review for the bot.

I did check the code though, and the bool change looks fine based on the issue described.

**Pull request merged**
