### PR TITLE
Add support for future ETABS versions

### LINKED ISSUE #391: ETABS_Toolkit: Add support for ETABS19
#### Description:

Addign build support for ETABS19

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #391 

 

WIth the API changed for Etabs from version 18 and onwards, the API is stated to work for future versions of the software. Hence, refactoring the adapter to reflect this. The ETABS18ADapter is renamed ETABSAdapter, as it should work for 18, 19 and future versions, with no requirements for special builds.

Keeping the 2016 and 17 adapters as is for backwards compatibility with those versions of the software.

The initialisation code for starting ETABS has been changed for the new ETABSAdapter to start the latest version of ETABS installed on the system, rather than pointing at a particular source folder. This means this part of the code does not need to be updated for every release of the software, and mimics what has been done for SAP2000.

Also cleaned up a significant amount of unrequired usings of the api reference to simplify the code.
 ### Test files

Specific testfile to test versioning in here. To test the versioning, make sure you manually delete the Etabs18_adapter.dll file from the assemblies folder in ProgramData. On this PR the EtabsAdapter will be marked as prototype, but that will not be the case as soon as the dlls have been updated in the installer.:

https://burohappold.sharepoint.com/:f:/s/BHoM/EjQQjb2k76pDs0Nkecwaq4IBOHDMKP_yNS4dcZnx3nYpVA?e=ubLiiO

The ETABSAdapter should work as the previous ETABS18ADapter did. Regular test scripts or project scripts good to use as a test-case.

 ### Changelog

- Rename ETABS18Adapter to ETABSAdapter
- Make sure the ETABSAdapter starts the latest available version of ETABS on the computer

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by JosefTaylor — APPROVED** [review]
Checked with ETABS 19, works great!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Pull request merged**
