### PR TITLE
Align with changes to BarUniformTemperatureLoad and AreaUniformTemperatureLoad

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1074
https://github.com/BHoM/BHoM_Engine/pull/2138

### Changelog

- Align with changes from `BarTemperatureLoad` and `AreaTemperatureLoad` to `BarUniformTemperatureLoad` and `AreaUniformTemperatureLoad`

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check code compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check documentation compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check project compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright compliance

**Review by IsakNaslundBh — APPROVED** [review]
LGTM

**Pull request merged**
