### PR TITLE
Etabs toolkit issue169 update to changes in b ho m

### LINKED ISSUE #121: Etabs_Toolkit: Spelling errors and name updates for loads in BHoM
Aligning with changes made in https://github.com/BHoM/BHoM/issues/382

### LINKED ISSUE #169: Etabs_Toolkit: Update due to changes in Structures_oM
Update due to changes made in:

https://github.com/BHoM/BHoM/issues/464
https://github.com/BHoM/BHoM_Engine/issues/922

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/481
https://github.com/BHoM/BHoM_Engine/pull/951

 ### Issues addressed by this PR

 Closes #169 
Closes #121 

 

Updating toolkit to align with changes made in BHoM and Engine

@dlamianski @nirbhay93 FYI as well. Could not add you as reviewers

 ### Test files

Please test through as much of existing projects/scripts as possible to ensure the Etabs-link is still functioning as before

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by alelom** [comment]
Testing it between today and monday.

**Comment by IsakNaslundBh** [comment]
@alelom if you have some time, it would be nice to get at least the bare minimum testing done mroe or less now. Thanks

**Comment by al-fisher** [comment]
Thanks both

**Comment by alelom** [comment]
Yes sorry I didn't realize the priority when I wrote the message -- I've been testing it since the call and have something to share for our structures call this afternoon already. Will keep doing it as priority.

**Comment by IsakNaslundBh** [comment]
@alelom 

> Issue 1 - Pull of loads not working
Due to string naming mismatch. Will not add existing loads to the list of retrieved loads.
See Helpers/Load.cs:

This should be unrelated to any of the changes induced by this PR. It is an important one though! Can you make sure that there is an issue raised for it?

> Issue 2 - Bar force orientation mismatch
Not sure whether I am comparing correctly, however this does not seem correct:

Same as for Issue 1, should be unrelated to any of the changes made in this PR. Very important though, please raise issue!

For 3-5 I think it all relates to old datasets on your machine.

Please make sure you sync down 

https://github.com/BHoM/BHoM_Engine/pull/951
and https://github.com/BHoM/BHoM_Datasets/pull/3

and try the same again.

Problem about not being to be able to push elements without properties has been raised before https://github.com/BHoM/ETABS_Toolkit/issues/130 and should be no different before and after the changes made here.

**Pull request merged**
