### PR TITLE
Updating levels and Grids to target Geometry.SettingOut namespace instead of Architecture namespace

### LINKED ISSUE #207: ETABS_Toolkit: Respond to change in Geometry Engine - levels and grids
#### Parent issue(s) or Pull Request(s) causing the changes:
Levels moved from om.architecture.elements. to om.geometry.settingout.

#

#### Description:
Can't pull levels because the request looks for SettingOut.Level and RAM only has Architecture.Element.Level.

Find and replace BH.oM.Architecture.Elements with BH.oM.Geometry.SettingOut

### PR DESCRIPTION
**Pull request by JosefTaylor**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #207 

Replaced mention of oM.Architecture with oM.Geometry.SettingOut

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ETABS_Toolkit/PR_208-UpdateGridAndLevel?csf=1&e=ew2hP8

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@IsakNaslundBh @enarhi @kThorsager could you give a quick review?

**Comment by JosefTaylor** [comment]
So now I've tried to re-support Architectural levels, and it works for reading, however I can't get it to push them. I can't say I fully understand what's happening in CreateCollection. @IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
Push a fix that made CreateCollection crash for empty list of old levels.

Also added a testfile to description.

@kThorsager @enarhi would one of you be able to test again, please?

For the push test, you will need to open a new model, then push one version and check that it worked. Then Open a new model and test the second version.

**Comment by JosefTaylor** [comment]
Tested, thanks @IsakNaslundBh and @kThorsager!

**Pull request merged**
