### PR TITLE
Add inheritance of IImutable class for PierForce

### LINKED ISSUE #446: Fix beta-code-compliance failures
#### Broken rules:

https://github.com/BHoM/ETABS_Toolkit/pull/445/checks?check_run_id=22829236082

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

 Closes #446 

 

 ### Test files

check code-compliance

 ### Changelog

- Added `IImutable` inheritance to `PierForce` class to satisfy beta-code-compliance checks. 

 ### Additional comments

#447 to be actioned next milestone

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check code-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check compliance

**Review by IsakNaslundBh — APPROVED** [review]
Approving only on code review. Simple PR only adding interface already implicitly implemented via inheritance chain, hence 0 changes to code is expected.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
