### PR TITLE
Align with changes in oM and Engine on Reflection -> Base

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1339
https://github.com/BHoM/BHoM_Engine/pull/2729
https://github.com/BHoM/BHoM_Adapter/pull/318

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix project file ref. 4788218382

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Review by JosefTaylor — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, code-compliance, copyright-compliance, dataset-compliance, documentation-compliance, null-handling, project-compliance, ready-to-merge, serialisation

**Pull request merged**
