### PR TITLE
Fix null handling in FEMesh

### LINKED ISSUE #384: Reading FE mesh fails when mesh has 'None' property or has no nodes/faces
#### Description:

Reading FEMesh, if any meshes have no nodes, no faces, or no properties, the adapter crashes.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #384 

 
Also related to #352 

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/ETABS_Toolkit/%23385-fix-FEMesh-read-method?csf=1&web=1&e=1WOL2g

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Review by mchaf — APPROVED** [review]
LGTM, king

**Pull request merged**
